name: "Build slides"

on:
  push:
    branches:
      - "trunk"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4

      - name: "Setup PNPM"
        uses: "pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2" # v4
        with:
          version: "8"
          run_install: true

      - name: "Build slides"
        run: "pnpm build --base /cs202-design-patterns-seminar"

      - name: Fix permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: "Upload built slides"
        uses: "actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa" # v3
        with:
          path: "dist/"
  
  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: "Deploy site"
        id: "deployment"
        uses: "actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e" # v4


